export const EndPoint = {
    USER_REGISTER:'admin/register',
    USER_LOGIN:'admin/login',
    USER_GET:'users/teacher/get',
    USER_UPDATE:'users/teacher/update',
    USER_CREATE:'users/teacher/create',
    USER_DELETE:'users/teacher/delete',
    USER_VERIFY_EMAIL:'/auth/send-otp' ,
    USER_VERIFY_OTP:'auth/verify-otp',
    USER_FORGOT_PASSWORD:'/auth/forgot-password',
    ASSIGNMENT_CREATE:'assignments/create',
    ASSIGNMENT_GET:'assignments/get',
    ASSIGNMENT_UPDATE:'assignments/update',
    ASSIGNMENT_DELETE:'assignments/delete',
    TODOS_CREATE:'todos/create',
    TODOS_GET:'todos/get',
    TODOS_UPDATE:'todos/update',
}